remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
- jekyll-feed
- jekyll-sitemap
title: Awesome Database Tools
description: This blog showcases useful database tools and tips
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
baseurl: "/awesome-database-tools"
permalink: /:title/
