remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Awesome Database Tools
description: This blog showcases useful database tools and tips
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
baseurl: "/awesome-database-tools"
permalink: /:title/
